spring:
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  jwt:
    secret-key: "6f4f473c829417b43d6216ef072b3ca5e4322acaea75541e1b318226a8ea4474"